name: Build

on:
  pull_request:
  push:
    branches:
    - develop
    - main
    - release/*
    tags: '[0-9]+.[0-9]+.[0-9]+'
  release:
    types:
    - created
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 1m
# asd
