name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-bamboo-variants:
    name: Build and Push the Docker Images for the Bamboo variants
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: swift
            version: 7.2.5
            platforms: linux/amd64

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: artemis-bamboo-${{ matrix.name }}
          restore-keys: |
            artemis-bamboo-${{ matrix.name }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./bamboo/${{ matrix.name }}
          file: ./bamboo/${{ matrix.name }}/Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ghcr.io/hialus/artemis-bamboo:latest-${{ matrix.name }},ghcr.io/hialus/artemis-bamboo:${{ matrix.version }}-${{ matrix.name }}
          labels: "runnumber=${GITHUB_RUN_ID}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
