name: Deploy to Testserver

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "A"
            b: 1
          - name: "B"
            b: 2
    outputs:
      matrix: ${{ toJSON(steps.output.outputs.*) }}
    steps:
      - id: matrix
        env:
          MATRIX_JSON: ${{ toJSON(matrix) }}
        run: |
          echo '${{ matrix.name }}=$MATRIX_JSON' >> $GITHUB_OUTPUT
#         echo '${{ matrix.name }}=\'${{ toJSON(matrix) }}\'' >> $GITHUB_OUTPUT
#         echo '::set-output name=value::[{"name":"A","b":"1"},{"name":"B","b":"2"}]'
          
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    #strategy:
    #  matrix: 
    #    include: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ needs.setup.outputs.matrix }}"
#         echo "${{ matrix.name }} & ${{ matrix.b }}"
