name: Deploy to Testserver

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "A"
            b: 1
          - name: "B"
            b: 2
    outputs:
      matrix: ${{ toJSON(steps.output.outputs.*) }}
    steps:
      - id: matrix
        run: |
          echo '${{ matrix.name }}=$(echo \'${{ toJSON(matrix) }}\' | tr -d '\n')' >> $GITHUB_OUTPUT
#         echo '${{ matrix.name }}=\'${{ toJSON(matrix) }}\'' >> $GITHUB_OUTPUT
#         echo '::set-output name=value::[{"name":"A","b":"1"},{"name":"B","b":"2"}]'
          
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.name }} & ${{ matrix.b }}"
