name: Deploy to Testserver

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "A"
            b: 1
            c: true
          - name: "B"
            b: 2
            c: true
          - name: "C"
            b: 3
            c: false
    outputs:
      matrix: ${{ toJSON(steps.matrix.outputs.*) }}
      A: ${{ steps.matrix.outputs.A || '' }}
      B: ${{ steps.matrix.outputs.B || '' }}
    steps:
      - id: matrix
        env:
          MATRIX_JSON: ${{ toJSON(matrix) }}
        if: matrix.c
        run: |
          MATRIX_JSON=${MATRIX_JSON//$'\n'/}
          MATRIX_JSON=${MATRIX_JSON//$'"'/"'"}
          echo "${{ matrix.name }}=$MATRIX_JSON" >> $GITHUB_OUTPUT
#         echo '${{ matrix.name }}=\'${{ toJSON(matrix) }}\'' >> $GITHUB_OUTPUT
#         echo '::set-output name=value::[{"name":"A","b":"1"},{"name":"B","b":"2"}]'
          
  echo:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.setup.outputs.matrix }}"
          echo "${{ toJSON(needs.setup.outputs.*) }}"

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{needs.setup.outputs.*}}
    steps:
      - run: |
          echo "${{ matrix.name }} & ${{ matrix.b }}"
