name: Build testing
# 1a

on:
  pull_request:
  push:
    branches:
      - main
      
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    concurrency:
      group: test1
    steps:
      - name: Sleep
        run: |
          sleep 10m
  test2:
    name: Test 2
    runs-on: ubuntu-latest
    concurrency:
      group: test2
    steps:
      - name: Sleep
        run: |
          sleep 20m
  test3:
    name: Test 3
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: |
          sleep 2m
